<a href="https://colab.research.google.com/github/saravana4374/project01/blob/main/Copy_of_jupyter_notebooks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
df=pd.read_csv("ecommerce_sales_dataset_50000.csv")
df

,order_id,customer_id,customer_name,product,category,price,quantity,total_amount,order_date,city,country,payment_method,rating
0,ORD000001,CUST12067,Allison Hill,Yoga Mat,Sports,42.39,3,127.17,2023-10-13,Los Angeles,USA,Credit Card,NaN
1,ORD000002,CUST03583,Noah Rhodes,Running Shoes,Sports,134.97,4,539.88,2023-07-11,Mumbai,India,Debit Card,5.0
2,ORD000003,CUST09655,Angie Henderson,Shampoo,Beauty,844.06,5,4220.30,2025-07-08,Berlin,Germany,UPI,NaN
3,ORD000004,CUST02548,Daniel Wagner,Action Figure,Toys,1139.42,2,2278.84,2024-07-23,Munich,Germany,Debit Card,NaN
4,ORD000005,CUST13224,Cristian Santos,Blender,Home & Kitchen,143.66,1,143.66,2024-06-25,Manchester,UK,Credit Card,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD049996,CUST00712,Kenneth Cantu,Comic Book,Books,197.27,4,789.08,2023-07-02,Hyderabad,India,Credit Card,2.0
49996,ORD049997,CUST02448,Carmen Wilson,Running Shoes,Sports,1071.28,5,5356.40,2023-12-18,Melbourne,Australia,Credit Card,3.0
49997,ORD049998,CUST12784,Rachel Reed,Sunscreen,Beauty,1462.93,4,5851.72,2025-05-09,Chennai,India,UPI,3.0
49998,ORD049999,CUST04996,April Edwards,Jacket,Clothing,463.32,1,463.32,2024-05-21,Melbourne,Australia,Cash on Delivery,3.0
49999,ORD050000,CUST04887,Michael Brooks,Action Figure,Toys,27.06,2,54.12,2025-07-03,Los Angeles,USA,Net Banking,4.0

In [ ]:
df.isnull().sum()

order_id              0
customer_id           0
customer_name         0
product               0
category              0
price                 0
quantity              0
total_amount          0
order_date            0
city                  0
country               0
payment_method        0
rating            14255
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df.isnull().sum()

order_id          0
customer_id       0
customer_name     0
product           0
category          0
price             0
quantity          0
total_amount      0
order_date        0
city              0
country           0
payment_method    0
rating            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df

,order_id,customer_id,customer_name,product,category,price,quantity,total_amount,order_date,city,country,payment_method,rating
1,ORD000002,CUST03583,Noah Rhodes,Running Shoes,Sports,134.97,4,539.88,2023-07-11,Mumbai,India,Debit Card,5.0
5,ORD000006,CUST13589,Connie Lawrence,Comic Book,Books,191.62,4,766.48,2024-08-23,Coimbatore,India,PayPal,5.0
6,ORD000007,CUST12666,Abigail Shaffer,Board Game,Toys,868.14,1,868.14,2024-04-11,Hyderabad,India,UPI,1.0
7,ORD000008,CUST02665,Gina Moore,Puzzle,Toys,1300.39,4,5201.56,2025-01-17,Manchester,UK,UPI,3.0
8,ORD000009,CUST08752,Gabrielle Davis,Sneakers,Clothing,1054.22,1,1054.22,2023-12-17,Brisbane,Australia,PayPal,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD049996,CUST00712,Kenneth Cantu,Comic Book,Books,197.27,4,789.08,2023-07-02,Hyderabad,India,Credit Card,2.0
49996,ORD049997,CUST02448,Carmen Wilson,Running Shoes,Sports,1071.28,5,5356.40,2023-12-18,Melbourne,Australia,Credit Card,3.0
49997,ORD049998,CUST12784,Rachel Reed,Sunscreen,Beauty,1462.93,4,5851.72,2025-05-09,Chennai,India,UPI,3.0
49998,ORD049999,CUST04996,April Edwards,Jacket,Clothing,463.32,1,463.32,2024-05-21,Melbourne,Australia,Cash on Delivery,3.0
49999,ORD050000,CUST04887,Michael Brooks,Action Figure,Toys,27.06,2,54.12,2025-07-03,Los Angeles,USA,Net Banking,4.0